import type { Template } from './types'

/** SPEC §4: arepa stand in a Berlin Markthalle. Placeholder values until calibrated. */
export const arepaMarkthalle: Template = {
  id: 'arepa-markthalle',
  scenarioName: 'Arepa stand · Markthalle Berlin',
  uncertain: [
    {
      key: 'peakHours',
      label: 'Busy hours per day',
      unit: 'h',
      higherIsWorse: false,
      defaults: { worst: 2, base: 3, best: 4 },
      spread: { worst: -0.33, best: 0.33 },
      limits: { lower: 0, upper: { decision: 'openHours' } },
      help: 'How many hours of the day feel busy, e.g. the lunch rush.',
      tip: 'Watch a similar stall on a Saturday and note when queues form and when they fade.',
    },
    {
      key: 'peakDemand',
      label: 'Orders per busy hour',
      unit: 'orders/h',
      higherIsWorse: false,
      defaults: { worst: 10, base: 18, best: 28 },
      spread: { worst: -0.45, best: 0.55 },
      limits: { lower: 0, upper: 150 },
      help: 'How many customers want to order in a busy hour, even if you could not serve them all.',
      tip: 'Count orders at a similar stall during a Saturday lunch rush.',
    },
    {
      key: 'offpeakDemand',
      label: 'Orders per quiet hour',
      unit: 'orders/h',
      higherIsWorse: false,
      defaults: { worst: 3, base: 6, best: 10 },
      spread: { worst: -0.5, best: 0.65 },
      limits: { lower: 0, upper: 100 },
      help: 'How many customers want to order in a quiet hour.',
      tip: 'Count orders at a similar stall during a quiet afternoon hour.',
    },
    {
      key: 'avgSpendGross',
      label: 'Average spend per order',
      unit: '€',
      higherIsWorse: false,
      defaults: { worst: 10, base: 12, best: 14 },
      spread: { worst: -0.17, best: 0.17 },
      limits: { lower: 1, upper: 60 },
      help: 'What a customer pays on average per order, including VAT and drinks.',
      tip: 'Check what similar stalls charge, or test your menu and prices at a market day.',
    },
    {
      key: 'costPerOrder',
      label: 'Ingredients + packaging per order',
      unit: '€',
      higherIsWorse: true,
      defaults: { worst: 3.8, base: 3.2, best: 2.8 },
      spread: { worst: 0.2, best: -0.12 },
      limits: { lower: 0, upper: 30 },
      help: 'Food, drinks and packaging for an average order. Worst = most expensive.',
      tip: 'Price your recipes with real supplier quotes, including packaging.',
    },
  ],
  decisions: [
    { key: 'openHours', label: 'Opening hours', unit: 'h', default: 8, min: 1, max: 24, step: 0.5 },
    {
      key: 'capacityPerHour',
      label: 'Most orders you can serve per hour',
      unit: 'orders/h',
      default: 30,
      min: 1,
      step: 1,
    },
    {
      key: 'staffCount',
      label: 'Staff on shift (not counting you)',
      unit: 'people',
      default: 1,
      min: 0,
      step: 1,
    },
    { key: 'setupHours', label: 'Setup + cleanup hours', unit: 'h', default: 2, min: 0, step: 0.5 },
    {
      key: 'staffCostPerHour',
      label: 'Staff cost per hour (employer)',
      unit: '€/h',
      default: 18,
      min: 0,
      step: 0.5,
    },
    {
      key: 'ownerRatePerHour',
      label: 'Your own pay per hour',
      unit: '€/h',
      default: 18,
      min: 0,
      step: 0.5,
      help: 'You work the same hours as your staff. Set to 0 to see profit before paying yourself.',
    },
    { key: 'rentFixedPerDay', label: 'Rent per day', unit: '€', default: 120, min: 0, step: 5 },
    {
      key: 'rentRevenueShare',
      label: 'Rent: share of sales',
      unit: '%',
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      advanced: true,
    },
    {
      key: 'cardFeeRate',
      label: 'Card / payment fees',
      unit: '%',
      default: 0.015,
      min: 0,
      max: 1,
      step: 0.001,
      advanced: true,
    },
    {
      key: 'vatFood',
      label: 'VAT on food',
      unit: '%',
      default: 0.07,
      min: 0,
      max: 1,
      step: 0.01,
      advanced: true,
    },
    {
      key: 'vatDrinks',
      label: 'VAT on drinks',
      unit: '%',
      default: 0.19,
      min: 0,
      max: 1,
      step: 0.01,
      advanced: true,
    },
    {
      key: 'drinksShare',
      label: 'Drinks share of sales',
      unit: '%',
      default: 0.2,
      min: 0,
      max: 1,
      step: 0.01,
      advanced: true,
    },
    {
      key: 'otherCostsPerDay',
      label: 'Other costs per day',
      unit: '€',
      default: 25,
      min: 0,
      step: 5,
      help: 'Energy, cleaning, waste, small consumables.',
    },
  ],
  correlations: [
    { a: 'peakDemand', b: 'offpeakDemand', rho: 0.6 },
    { a: 'avgSpendGross', b: 'peakDemand', rho: -0.2 },
    { a: 'avgSpendGross', b: 'offpeakDemand', rho: -0.2 },
    { a: 'avgSpendGross', b: 'costPerOrder', rho: 0.3 },
  ],
}
